### ISSUE TITLE
Discord login failure - Docker shuts down.

### ISSUE THREAD

**Issue by Endlaw** [pejter/dockerfiles#1]
Hey Pejter, 

Can you help me understand how to get this to load in unraid?  

I have the files all extracted / loaded properly i believe, however there is no reference material for the Discord related fields... 

built on Oct 21 2017 13:44:17 with gcc 4.9.2 (Debian 4.9.2-10)
Logging into Discord...
No credentials available to login.
[10/01/2018 11:17] ERROR red <module> 634: Fatal exception, attempting graceful logout

![capture](https://user-images.githubusercontent.com/35305547/34789398-51b812d6-f5fb-11e7-827a-22e31888547c.JPG)

**Comment by Telain** [comment]
I'm having the same issue, trying to track down how to get these settings in.

**Comment by Telain** [comment]
I managed to get it going by copying the token from the discord bot creation (https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token) to data\red\settings.json. Put it in quotes in the token field.

I also copied the contents of the cog and data directories here (https://github.com/Cog-Creators/Red-DiscordBot) into those directories in the docker's appdata. Not sure if that was necessary or not, but I was getting this error too that that seemed to fix.

```
File "./red.py", line 21, in <module>
from cogs.utils.settings import Settings
ModuleNotFoundError: No module named 'cogs.utils'
avconv version 11.11-6:11.11-1~deb8u1, Copyright (c) 2000-2017 the Libav developers
```

**Comment by pejter** [comment]
Sorry for the late response, busy week at work.
### Missing config
The bot needs a valid config & cog data which can either be entered when first running it through the CLI or into the config file directly.

However when not running the container in interactive mode (the `-it` options) there is no one to respond to the question about the bot token so the latter option becomes necessary.

### cogs and data volumes
When it comes to the data & cogs directories I haven't considered that host bind-mounts have a different behaviour when it comes to the propagation of existing files. Docker volumes copy the existing files into the volume but bind mounts overwrite the files from the host directory.

Many people are using bind-mounts instead of docker managed volumes to persist their data and there is a couple of ways to handle this issue.

### Summary
I'd recommend opening a different issue for the bind-mount problem. I'll add the config step to the readme & close this issue.
